# Generated by Django 4.0.4 on 2024-10-21 07:29

from django.db import migrations, models
import muninn.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(default='Enter your grade', max_length=100)),
                ('subject', models.CharField(default='Enter your subject', max_length=100)),
                ('chapter', models.CharField(default='Chapter Name', max_length=100)),
                ('sut', models.CharField(default='NOT INITIALIZED', max_length=10000)),
                ('t', models.CharField(default=muninn.models.generate_timestamp, max_length=100)),
                ('identity', models.IntegerField(default=0)),
                ('pdf', models.FileField(upload_to=muninn.models.get_upload_path)),
                ('fa', models.JSONField(default=list)),
                ('fq', models.JSONField(default=list)),
                ('questions', models.JSONField(default=list)),
                ('answers', models.JSONField(default=list)),
                ('grades', models.JSONField(default=list)),
                ('remarks', models.JSONField(default=list)),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
    ]
